name: ${pluginName}DebugPlugin
version: ${version}
main: ${group}.${packageName}.debug.plugin.${pluginName}DebugPlugin
api-version: 1.19
libraries:
  - io.github.monun:kommand-core:3.1.6
  - io.github.muqhc:skygui:0.3.3