name: ${pluginName}DebugPlugin
version: ${version}
main: ${group}.${packageName}.debug.plugin.${pluginName}DebugPlugin
api-version: 1.19
libraries:
  - xyz.icetang.lib:icemmand-core:1.21.1+1.0.0
  - io.github.muqhc:skygui:0.3.3